# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

u1 = User.create(name: "Josefina", email: "josefina@miuandes.cl", city: "Santiago", country: "Chile", birthdate: "12-12-1997", biography: "Industrial engineering student, 21 years old, dog lover.", password: "123456789", password_confirmation: "123456789", terms:true, aup: true)
u2 = User.create(name: "Martin", email: "martin@miuandes.cl", city: "Lampa", country: "Chile", birthdate: "03-12-1996", biography: "Industrial engineering student, 22 years old, dog lover.", password: "123456789", password_confirmation: "123456789", terms:true, aup: true)
u3 = User.create(name: "Tomgarc", email: "tom@miuandes.cl", city: "Santiago", country: "Chile", birthdate: "03-12-1996", biography: "Industrial engineering student, 21 years old.", password: "123456789", password_confirmation: "123456789", terms:true, aup: true, status:false)
u4 = User.create(name: "Gorgor", email: "gorgor@miuandes.cl", city: "Santiago", country: "Chile", birthdate: "03-12-1996", biography: "Industrial engineering student, 21 years old.", password: "123456789", password_confirmation: "123456789", terms:true, aup: true, adm: true)
u5 = User.create(name: "Aspee", email: "aspee@miuandes.cl", city: "Viña del Mar", country: "Chile", birthdate: "03-12-1996", biography: "Industrial engineering student, 21 years old.", password: "123456789", password_confirmation: "123456789", terms:true, aup: true, adm: true, super_adm: true)

p1 = Post.create(title: "Used Lead-Acid Batteries", description: "According to Pure Earth, the industry dealing with ULAB is one of the world’s 10 most polluting industries. Lead-acid batteries are used for a number of purposes with their most common use being as automotive batteries in vehicles.Although these batteries are rechargeable, after a certain period, these batteries lose their capacity to hold the electrical charge. \n
	The unused batteries are graded as hazardous waste and enter the recycling industry where every part is upcycled. In most cases, industries do not maintain required safety standards and workers often use crude methods to handle toxic waste. Some of the steps of recycling the ULAB's are carried out in unprotected environments leading to the toxic waste contaminating nearby air and water.\n
		According to Pure Earth, 150 such sites have been identified and nearly 1 million people are at risk from the pollutants generated by this industry. ", city:"Stgo", country:"Chile", close: false, user_id: u1[:id])
p2 = Post.create(title: "Albert Einstein", description: "Albert Einstein (Alemán: /ˈalbɛɐ̯t ˈʔaɪnʃtaɪn/; Ulm, Imperio alemán, 14 de marzo de 1879-Princeton, Estados Unidos, 18 de abril de 1955) fue un físico alemán de origen judío, nacionalizado después suizo, austriaco y estadounidense. Se lo considera el científico más importante, conocido y popular del siglo XX.1​2​ En 1905, cuando era un joven físico desconocido, empleado en la Oficina de Patentes de Berna, publicó su teoría de la relatividad especial. En ella incorporó, en un marco teórico simple fundamentado en postulados físicos sencillos, conceptos y fenómenos estudiados antes por Henri Poincaré y por Hendrik Lorentz. Como una consecuencia lógica de esta teoría, dedujo la ecuación de la física más conocida a nivel popular: la equivalencia masa-energía, E=mc².\n
	Ese año publicó otros trabajos que sentarían algunas de las bases de la física estadística y de la mecánica cuántica. ", city:"Stgo", country:"Chile", close: false, user_id: u2[:id])
p3 = Post.create(title: "Child labour in fashion", description: "Around 260 million children are in employment around the world, according to the International Labour Organisation. Of them, the ILO estimates that 170 million are engaged in child labour, defined by the UN as “work for which the child is either too young – work done below the required minimum age – or work which, because of its detrimental nature or conditions, is altogether considered unacceptable for children and is prohibited”.\n
	Child labour is forbidden by law in most countries but continues to be rife in some of the poorest parts of the world.\n 
	The situation is improving. ILO estimates suggest child labour declined by 30% between 2000 and 2012, but still 11% of the world’s children are in situations that deprive them of their right to go to school without interference from work.\n
	Many of these child labourers work within the fashion supply chain, making the textiles and garments to satisfy the demand of consumers in Europe, the US, and beyond. ", city:"Stgo", country:"Chile", close: true, user_id: u2[:id])


d = Dumpster.create(post_id: p2[:id])
b = Blacklist.create(user_id: u3[:id])

i = InappropriateContent.create(user_id: u2[:id], post_id: p1[:id], description: 'I think this is inappropriate')
s = Share.create(user_id: u2[:id], post_id: p1[:id])
f = Follower.create(user_id: u4[:id], post_id: p1[:id])
l1 = Like.create(user_id: u4[:id], post_id: p1[:id])
l2 = Like.create(user_id: u5[:id], post_id: p1[:id])
l3 = Like.create(user_id: u4[:id], post_id: p3[:id])
l4 = Like.create(user_id: u5[:id], post_id: p3[:id])
l5 = Like.create(user_id: u1[:id], post_id: p3[:id])
d = Dislike.create(user_id: u2[:id], post_id: p1[:id])
c1 = Comment.create(user_id: u4[:id], post_id: p1[:id], description: '@Josefina We should do something')
c2 = Comment.create(user_id: u5[:id], post_id: p1[:id], description: 'Nice post!')
c3 = Comment.create(user_id: u1[:id], post_id: p1[:id], description: 'Why did you dislike the post? @Martin')

