GOOGLE_KEY: '1002912858068-e0n8322o7i7dro4e2ngnc421comujodu.apps.googleusercontent.com'
GOOGLE_SECRET: 'b_SVjmJRXpsN5rPWdClCHDhr'

GMAIL_USERNAME: 'crosspatch.web@gmail.com'
GMAIL_PASSWORD: 'crosspatch123'